# Generated by Django 5.1.4 on 2024-12-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_signatures/')),
                ('uploaded_signature', models.ImageField(upload_to='uploaded_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
